apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-no-rpc.yml -o k8s-no-rpc/ -n blueprint-hotel convert
    kompose.image-pull-policy: IfNotPresent
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: recomd-db
  name: recomd-db

spec:
  ports:
    - name: "12356"
      port: 12356
      targetPort: 27017
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: recomd-db
