apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-no-rpc.yml -o k8s-no-rpc/ -n blueprint-hotel
      convert
    kompose.image-pull-policy: IfNotPresent
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: reserv-cache
  name: reserv-cache

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reserv-cache
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-no-rpc.yml -o k8s-no-rpc/ -n blueprint-hotel
          convert
        kompose.image-pull-policy: IfNotPresent
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: reserv-cache
    spec:
      containers:
      - image: memcached
        imagePullPolicy: IfNotPresent
        name: reserv-cache-ctr
        ports:
        - containerPort: 11211
          protocol: TCP
      hostname: reserv-cache
      restartPolicy: Always
