apiVersion: v1
data:
  JAEGER_DIAL_ADDR: jaeger:14268
  RESERV_CACHE_DIAL_ADDR: reserv-cache:11211
  RESERV_DB_DIAL_ADDR: reserv-db:27017
  RESERV_SERVICE_GRPC_BIND_ADDR: 0.0.0.0:12345
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: reserv-service-container-reserv-service-container-env
  name: reserv-service-container-env
