apiVersion: v1
data:
  JAEGER_DIAL_ADDR: jaeger:14268
  RATE_CACHE_DIAL_ADDR: rate-cache:11211
  RATE_DB_DIAL_ADDR: rate-db:27017
  RATE_SERVICE_GRPC_BIND_ADDR: 0.0.0.0:12345
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: rate-service-container-rate-service-container-env
  name: rate-service-container-env
