apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-no-rpc.yml -o k8s-no-rpc/ -n blueprint-hotel
      convert
    kompose.image-pull-policy: IfNotPresent
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: user-db
  name: user-db

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-no-rpc.yml -o k8s-no-rpc/ -n blueprint-hotel
          convert
        kompose.image-pull-policy: IfNotPresent
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: user-db
    spec:
      containers:
      - image: mongo
        imagePullPolicy: IfNotPresent
        name: user-db-ctr
        ports:
        - containerPort: 27017
          protocol: TCP
      hostname: user-db
      restartPolicy: Always
