apiVersion: v1
data:
  JAEGER_DIAL_ADDR: jaeger:14268
  USER_DB_DIAL_ADDR: user-db:27017
  USER_SERVICE_GRPC_BIND_ADDR: 0.0.0.0:12345
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: user-service-container-user-service-container-env
  name: user-service-container-env
