apiVersion: v1
data:
  JAEGER_DIAL_ADDR: jaeger:14268
  PROFILE_CACHE_DIAL_ADDR: profile-cache:11211
  PROFILE_DB_DIAL_ADDR: profile-db:27017
  PROFILE_SERVICE_GRPC_BIND_ADDR: 0.0.0.0:12345
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: profile-service-container-profile-service-container-env
  name: profile-service-container-env
